## Importing neccessary modules

In [1]:
import re
import pandas as pd
import numpy as np

## Loading data

In [2]:
data=pd.read_csv(r"K:\Desktop\NIIT\tables\DS3_C2_S1_Tweets_Data_Challenge.csv")
data

,id,keyword,location,text,target
0,0,ablaze,NaN,"Communal violence in Bhainsa, Telangana. ""Ston...",1
1,1,ablaze,NaN,Telangana: Section 144 has been imposed in Bha...,1
2,2,ablaze,New York City,Arsonist sets cars ablaze at dealership https:...,1
3,3,ablaze,"Morgantown, WV",Arsonist sets cars ablaze at dealership https:...,1
4,4,ablaze,NaN,"""Lord Jesus, your love brings freedom and pard...",0
...,...,...,...,...,...
11365,11365,wrecked,Blue State in a red sea,Media should have warned us well in advance. T...,0
11366,11366,wrecked,arohaonces,i feel directly attacked ðŸ’€ i consider moonbin ...,0
11367,11367,wrecked,ðŸ‡µðŸ‡­,i feel directly attacked ðŸ’€ i consider moonbin ...,0
11368,11368,wrecked,auroraborealis,"ok who remember ""outcast"" nd the ""dora"" au?? T...",0
11369,11369,wrecked,NaN,Jake Corway wrecked while running 14th at IRP.,1

## Task1

In [3]:
string_filter=data[(data.text.str.contains('crash')) | (data.text.str.contains('quarantine')) | (data.text.str.contains('brush fires'))]

In [4]:
string_filter

,id,keyword,location,text,target
187,187,airplane%20accident,NaN,Germany's Foreign Minister Heiko Maas says 'It...,1
2624,2624,crash,Jakarta,"Boeing called Lion Air ""idiotsâ€™', and denied t...",0
2626,2626,crash,Everywhere,"#Iran, grappling with unrest over the Ukrainia...",1
2627,2627,crash,"London, England",It is now timely to make all the profits possi...,0
2628,2628,crash,Russia. In the dense forests.,BREAKING: Iranian Judiciary spokesman says sev...,1
...,...,...,...,...,...
9201,9201,sinking,morocco,We've all had that sinking feeling when we ope...,0
9232,9232,sinking,United Arab Emirates,We've all had that sinking feeling when we ope...,0
11304,11304,wreckage,NaN,Ukraine deliberately issued statement after Ir...,1
11309,11309,wreckage,NaN,Iran plane crash wreckage spotted from space (...,1
11317,11317,wreckage,Canada,American Media said that Iran had bulldozed th...,0

In [5]:
string_filter=string_filter.dropna()

In [6]:
string_filter[['location']]

                            location
2624                         Jakarta
2626                      Everywhere
2627                 London, England
2628   Russia. In the dense forests.
2634     Cape Cod, Massachusetts USA
...                              ...
8774                Indianapolis, IN
8843                     Walsall, UK
9201                         morocco
9232            United Arab Emirates
11317                         Canada

[111 rows x 1 columns]

## Task2

In [7]:
text=" ".join(i for i in string_filter.text)

In [8]:
clean_text=re.sub(r'[^a-zA-Z]+',' ',text)

In [9]:
clean_text

'Boeing called Lion Air idiots and denied their request for Boeing Max training before deadly crash It s bad e Iran grappling with unrest over the Ukrainian plane crash warns protesters it will do everything necessary to protect the p It is now timely to make all the profits possible before a fiscal crash this is an excellent encouraging tip https t co ICsETX Six BREAKING Iranian Judiciary spokesman says several arrested for their role in Ukraine plane crash reports https t co uZ UPDATED Mashpee ambulance with patient on board involved in multiple vehicle crash six patients transported to ar https t co cBW GjUpoc Iran says some people arrested for their role in Ukrainian plane crash https t co hFADsZKRPH when the Amazon drone techs gotta do crash testing https t co m Iu xWJYU I repeat what I said last week after car crash interview on GMS let s hope she gets elected Labour Leader Three Kwankwasiyya members killed in auto crash News Fact News Online https t co bkIFPLFbm Live as M drivers face four miles of queues after crash near Slough driving news https t co cXrtD u B Weapons yielding thieves crash getaway car leave pawnshop workers extremely shaken T NEWS https t co NwLibBej Bose QC price crash premium wireless headphones dropped to lowest ever price NEWPAPER https t co IyfbUDGAFU bro how is my internet gonna crash in a middle of a league match Mandy the cat came first while matt was still recovering from the citadel crash and before kaidan stepped down as a https t co a MyNmsiw Arrestaties in Iran in verband met crash Boeing https t co FkfMJyCILs Three morning stories Iran vows to punish those responsible for plane crash https t co mvoh bPai PM C https t co O wmTNFBY Canada s Trudeau Iran plane crash victims would be alive had there been no tension in region https t co RaQoyLebSI https BoundaryStones years ago today Washington mourned two unrelated but deadly tragedies the crash of Flight i https t co IX Mpwe iP Why are you still calling it a plane crash https t co lLCCbCB sD Did I crash at pm yesterday and woke up just now I hope this causes Bernie to crash and bern So sick of it https t co A All ready for the website to crash trying to get West Ham fa cup tickets Benefits having away season ticket wba This was an absolutely car crash interview by Now bored of racism being used to win an argument https t Story of ModernWarfare crash every single moment and lose all the progression for that gold camo because dev at https t co rUxKAO g Nah I want to start wearing suits more But the opportunity never presents itself I should just crash a wedding https t co QtIth Aau Don t rush the come up by trying to impress folks that s how you become a crash dummy Canada s Trudeau addresses US role in deadly Iran plane crash https t co B MmKgf kj Without recent escalations Iran plane crash victims would be home with their families Justin Trudeau THIS is the Breaking Some people were arrested over Ukrainian aircraft crash in Iran media reports A man s died after a serious crash in Hanbury in Worcestershire yesterday afternoon HeartNews https t co jprAGzwHUL BREAKING Several people have been arrested because of their role in the Ukrainian plane crash in Iran that killed https t co scWtzlb Ku They hear ur having a bad time no sympathy hear u starving no help hear ur business has crashed no aid hear y https t co dgZ ncteH UNIAN info the Ukrainian plane that crashed killing all its victims in Iran would have faced the same fate beca https t co BwLFWUySbo Racksterly has crashed A crashed car turns into a man being shot dead https t co Z z AfG via The women were doing a left turn when the guy crashed into them coming from behind He was speeding about km h https t co m DPHJKxOc ARMY Apparently as it seems CONNECTBTS ONLINE is a new website as rumours say a lot searched amp crashed hints Damn almost crashed cuz I was falling asleep on the wheel whoops Driver of stolen tractor trailer killed when truck crashed into a car amp then another at Eglinton Mavis in Mississauga Other Meteorite that crashed in found to contain most ancient matter on Earth https t co phPrIy au for Kiana another victim in the crashed airplane https t co dIT dZK s On Wednesday Jan a jetliner operated by Ukrainian International Airlines crashed shortly after taking off in Iran Al Yesterday I slept from a a today I crashed at like pm Woke up at am and now I m ready to go for the day I guess It would have crashed into all for sure Should put this pic side by side with one that shows him CLEARLY FLYING HIGH Can t tell if he crashed here or what H fix charls left game crashed gee princess beer My laptop crashed I couldn t write any code and I slept thinking about how I could have become Mark Zuckerberg if https t co kMZBTGDGL crashed my car The NHS IT systems crashed at our GP practice this morning As a result I ran minutes late seeing my patients GP One of the biggest meteorite crashes in Earth s history flung debris across continents years ago Scientists finally Likely to increase deaths from road crashes violence suicides and drowning What the hell kind of research is this Emergency services at scene of multi vehicle crash near Muff https t co oNZ m P MA donegal New blog post The Inquisition To me I think emotions are like huge waves crashing against me I don t feel the emoti The plane doesn t crash immediately but is set on fire by the missile explosion We don t know the precise flig This evening I spoke with about the fatal plane crash in Iran and the need for a thorough amp credible investi Badminton king Momota faces two months out after fatal car crash https t co PFPkSk Fx https t co PFPkSk Fx Hey non Australians It s a bush fire The equivalent to a forest fire anywhere else Calling them brush fires seri https t co WoDj FNeoi Remember when four airplanes were hijacked amp crashed on Remember how there were no survivors amp no plane parts we RT from Jalopnik Michigan s mph speed limit has lead to more speeding crashes and injuries report https t co kYpRy qtnN RT from Jalopnik Michigan s mph speed limit has lead to more speeding crashes and injuries report https t co IpldR hs c Dr M on influenza outbreak We ll look into quarantine if situation persists https t co bCNeO cwmV my cats are in quarantine here FUCK https t co Cl kE cQMs As it seems to be fairly contagious I m thinking that we re looking at a full quarantine scenario I m sorrryyy I ll quarantine myself tomorrow I ve been sneezing ever since I got home Dr M on influenza outbreak We ll look into quarantine if situation persists https t co bCNeO cwmV Is she in a walking quarantine shield from him Someone s gonna have to quarantine the entire French Quarter tomorrow morning It s going to be a serious biohazard In the quarantine room at the biocontrol centre of at the to check out what Ugandan PhD student Agil Katu Somebody come quarantine this nigga until we can decide if he can be around society or not https t co wAqblDMB B No reason to quarantine This is the scent of dead skin on a linoleum floor This is the scent of quarantine wings in a hospital It s not so https t co AoiR ModP clear the quarantine Belated Hannukah Christmas and Happy New Year Here s Charlie recovering in quarantine from black mold exposure https t co Qmr lT yZ Thanks Jocelyn We brought our cat here from Myanmar via quarantine in Singapore and Melbourne and this https t co M MXkM ODJ Here s a picture of me in quarantine I took this when I started to feel better lmfaoo https t co vPkIx Zz They should quarantine assholes The disease is beyond treatment quarantine the vector of this disease please IslamicTerrorism Heavily medicated like they re quarantined https t co QhGs USbCr Victims of the anomaly are kept in a quarantined medical bay where they receive careful treatment All four victims Chinese woman with mystery virus quarantined in Thailand https t co LmgPP wQX Chinese woman with mystery virus quarantined in Thailand https t co j tk Fzt https t co Q hyPFgJeI Sorry You re quarantined now Woman with new coronavirus quarantined in Thailand st case outside China https t co vho n pzS And tell them if they get mc and must be quarantined they should stay at home amp not go to work Safe U mean quarantined https t co IIteSUzsk Chinese woman with mystery virus quarantined in Thailand https t co zALDWrbYDl Lmfao you need to be quarantined man he killed so much it became boring Hey if you want to put your child at risk feel free to stay quarantined away from the rest of the public Wow y all need to be quarantined and by quarantined I mean exterminated https t co BPTMx Ops Woman with new coronavirus quarantined in Thailand st case outside China https t co aCRPcTVwPx https t co b IBcgFW Update on me not catching the flu from my brother he text me from the room he s been quarantined in He needed foo https t co NSk Tlw o We got a new baby today She ll move into the big cage with natsu in maybe a week after shes quarantined but shes https t co tP PHOwgT Bourbon street bout to be quarantined Chinese woman with mysterious virus quarantined in Thailand https t co WszPiDwgfV A Chinese woman has been quarantined in Thailand with a mystery strain of coronavirus just days ahead of the Lunar https t co SmJO Fs K I had team mates international consultants quarantined in homestay on their retur https t co QYP gAktuw I don t know but they should be quarantined so as to not infect the rest of us Women that do this to anything other than a dick are gross specimens who need to be quarantined https t co xnRsS NXH A woman has been quarantined in Thailand First instance of de infection going international Thai Authorities ar https t co MALTvlJw You know you ve struck a nerve when replies start getting quarantined You need to be quarantined im RAINBOW evit has to keep me quarantined Chinese woman with mystery virus quarantined in Thailand https t co cgZpsvPnDP Thailand confirms first case of mystery virus from Wuhan Chinese woman quarantined https t co N StoxC s https t co C vmsc lR Chinese woman quarantined in Thailand is diagnosed with the same mystery virus that has killed one person in C https t co vrVScOl Jm Man charged after north east motorists crash into boulders and rubble shed from lorry https t co zjJWb IMi https t co U d MLjJmP Men are afraid They ve been told their life has to be lived a certain way and when it all crashes down he s left with r OTD in Thierry Sabine founder of the Paris Dakar Rally dies on a helicopter crash while taking part in the organi We ve all had that sinking feeling when we open a kitchen cupboard only to have everything come crashing down Follow these We ve all had that sinking feeling when we open a kitchen cupboard only to have everything come crashing down Fo https t co bZhE DCUJi American Media said that Iran had bulldozed the crash site of the shoot down What Iran did was relocate the wreckage It '

## Task3

In [14]:
text2=data[data.text.str.contains('magnitude')]
data[data.text.str.contains('magnitude')][['location']].dropna()

                       location
67                       Global
78                        Texas
79                sÃ£o paulo -sp
82           Flatbush, Brooklyn
86                       ethers
106         Wilmington, NC- USA
110                         NYC
1827                      Japan
4198     California, USA, Earth
4604                    Send me
4637              United States
4638  Jigjidjav St, Ulaanbaatar
6346              Illinois, USA

In [11]:
pattern = r'\d+\.\d+'

In [16]:
text2=" ".join(i for i in text2.text)

In [17]:
magnitude=re.findall(pattern,text2)

In [18]:
average=np.mean([float(i) for i in magnitude])

In [19]:
print("Earthquake magnitude = ",average)

Earthquake magnitude =  5.528571428571429

In [20]:
acc=data[data.text.str.contains('accident')]
acc[['location']].dropna()

                  location
38                 Nigeria
41              Covina, Ca
42      Colorado, Brighton
44     North Carolina, USA
47                      60
...                    ...
5433    Ft. Lauderdale, FL
6586      philadelphia, pa
6902   North Carolina, USA
9631   Islamabad, Pakistan
10536         Nowhere, man

[61 rows x 1 columns]

In [21]:
text3=" ".join(i for i in acc.text)

clean_text=re.sub(r'[^a-zA-Z]+',' ',text)

clean_text

'Boeing called Lion Air idiots and denied their request for Boeing Max training before deadly crash It s bad e Iran grappling with unrest over the Ukrainian plane crash warns protesters it will do everything necessary to protect the p It is now timely to make all the profits possible before a fiscal crash this is an excellent encouraging tip https t co ICsETX Six BREAKING Iranian Judiciary spokesman says several arrested for their role in Ukraine plane crash reports https t co uZ UPDATED Mashpee ambulance with patient on board involved in multiple vehicle crash six patients transported to ar https t co cBW GjUpoc Iran says some people arrested for their role in Ukrainian plane crash https t co hFADsZKRPH when the Amazon drone techs gotta do crash testing https t co m Iu xWJYU I repeat what I said last week after car crash interview on GMS let s hope she gets elected Labour Leader Three Kwankwasiyya members killed in auto crash News Fact News Online https t co bkIFPLFbm Live as M drivers face four miles of queues after crash near Slough driving news https t co cXrtD u B Weapons yielding thieves crash getaway car leave pawnshop workers extremely shaken T NEWS https t co NwLibBej Bose QC price crash premium wireless headphones dropped to lowest ever price NEWPAPER https t co IyfbUDGAFU bro how is my internet gonna crash in a middle of a league match Mandy the cat came first while matt was still recovering from the citadel crash and before kaidan stepped down as a https t co a MyNmsiw Arrestaties in Iran in verband met crash Boeing https t co FkfMJyCILs Three morning stories Iran vows to punish those responsible for plane crash https t co mvoh bPai PM C https t co O wmTNFBY Canada s Trudeau Iran plane crash victims would be alive had there been no tension in region https t co RaQoyLebSI https BoundaryStones years ago today Washington mourned two unrelated but deadly tragedies the crash of Flight i https t co IX Mpwe iP Why are you still calling it a plane crash https t co lLCCbCB sD Did I crash at pm yesterday and woke up just now I hope this causes Bernie to crash and bern So sick of it https t co A All ready for the website to crash trying to get West Ham fa cup tickets Benefits having away season ticket wba This was an absolutely car crash interview by Now bored of racism being used to win an argument https t Story of ModernWarfare crash every single moment and lose all the progression for that gold camo because dev at https t co rUxKAO g Nah I want to start wearing suits more But the opportunity never presents itself I should just crash a wedding https t co QtIth Aau Don t rush the come up by trying to impress folks that s how you become a crash dummy Canada s Trudeau addresses US role in deadly Iran plane crash https t co B MmKgf kj Without recent escalations Iran plane crash victims would be home with their families Justin Trudeau THIS is the Breaking Some people were arrested over Ukrainian aircraft crash in Iran media reports A man s died after a serious crash in Hanbury in Worcestershire yesterday afternoon HeartNews https t co jprAGzwHUL BREAKING Several people have been arrested because of their role in the Ukrainian plane crash in Iran that killed https t co scWtzlb Ku They hear ur having a bad time no sympathy hear u starving no help hear ur business has crashed no aid hear y https t co dgZ ncteH UNIAN info the Ukrainian plane that crashed killing all its victims in Iran would have faced the same fate beca https t co BwLFWUySbo Racksterly has crashed A crashed car turns into a man being shot dead https t co Z z AfG via The women were doing a left turn when the guy crashed into them coming from behind He was speeding about km h https t co m DPHJKxOc ARMY Apparently as it seems CONNECTBTS ONLINE is a new website as rumours say a lot searched amp crashed hints Damn almost crashed cuz I was falling asleep on the wheel whoops Driver of stolen tractor trailer killed when truck crashed into a car amp then another at Eglinton Mavis in Mississauga Other Meteorite that crashed in found to contain most ancient matter on Earth https t co phPrIy au for Kiana another victim in the crashed airplane https t co dIT dZK s On Wednesday Jan a jetliner operated by Ukrainian International Airlines crashed shortly after taking off in Iran Al Yesterday I slept from a a today I crashed at like pm Woke up at am and now I m ready to go for the day I guess It would have crashed into all for sure Should put this pic side by side with one that shows him CLEARLY FLYING HIGH Can t tell if he crashed here or what H fix charls left game crashed gee princess beer My laptop crashed I couldn t write any code and I slept thinking about how I could have become Mark Zuckerberg if https t co kMZBTGDGL crashed my car The NHS IT systems crashed at our GP practice this morning As a result I ran minutes late seeing my patients GP One of the biggest meteorite crashes in Earth s history flung debris across continents years ago Scientists finally Likely to increase deaths from road crashes violence suicides and drowning What the hell kind of research is this Emergency services at scene of multi vehicle crash near Muff https t co oNZ m P MA donegal New blog post The Inquisition To me I think emotions are like huge waves crashing against me I don t feel the emoti The plane doesn t crash immediately but is set on fire by the missile explosion We don t know the precise flig This evening I spoke with about the fatal plane crash in Iran and the need for a thorough amp credible investi Badminton king Momota faces two months out after fatal car crash https t co PFPkSk Fx https t co PFPkSk Fx Hey non Australians It s a bush fire The equivalent to a forest fire anywhere else Calling them brush fires seri https t co WoDj FNeoi Remember when four airplanes were hijacked amp crashed on Remember how there were no survivors amp no plane parts we RT from Jalopnik Michigan s mph speed limit has lead to more speeding crashes and injuries report https t co kYpRy qtnN RT from Jalopnik Michigan s mph speed limit has lead to more speeding crashes and injuries report https t co IpldR hs c Dr M on influenza outbreak We ll look into quarantine if situation persists https t co bCNeO cwmV my cats are in quarantine here FUCK https t co Cl kE cQMs As it seems to be fairly contagious I m thinking that we re looking at a full quarantine scenario I m sorrryyy I ll quarantine myself tomorrow I ve been sneezing ever since I got home Dr M on influenza outbreak We ll look into quarantine if situation persists https t co bCNeO cwmV Is she in a walking quarantine shield from him Someone s gonna have to quarantine the entire French Quarter tomorrow morning It s going to be a serious biohazard In the quarantine room at the biocontrol centre of at the to check out what Ugandan PhD student Agil Katu Somebody come quarantine this nigga until we can decide if he can be around society or not https t co wAqblDMB B No reason to quarantine This is the scent of dead skin on a linoleum floor This is the scent of quarantine wings in a hospital It s not so https t co AoiR ModP clear the quarantine Belated Hannukah Christmas and Happy New Year Here s Charlie recovering in quarantine from black mold exposure https t co Qmr lT yZ Thanks Jocelyn We brought our cat here from Myanmar via quarantine in Singapore and Melbourne and this https t co M MXkM ODJ Here s a picture of me in quarantine I took this when I started to feel better lmfaoo https t co vPkIx Zz They should quarantine assholes The disease is beyond treatment quarantine the vector of this disease please IslamicTerrorism Heavily medicated like they re quarantined https t co QhGs USbCr Victims of the anomaly are kept in a quarantined medical bay where they receive careful treatment All four victims Chinese woman with mystery virus quarantined in Thailand https t co LmgPP wQX Chinese woman with mystery virus quarantined in Thailand https t co j tk Fzt https t co Q hyPFgJeI Sorry You re quarantined now Woman with new coronavirus quarantined in Thailand st case outside China https t co vho n pzS And tell them if they get mc and must be quarantined they should stay at home amp not go to work Safe U mean quarantined https t co IIteSUzsk Chinese woman with mystery virus quarantined in Thailand https t co zALDWrbYDl Lmfao you need to be quarantined man he killed so much it became boring Hey if you want to put your child at risk feel free to stay quarantined away from the rest of the public Wow y all need to be quarantined and by quarantined I mean exterminated https t co BPTMx Ops Woman with new coronavirus quarantined in Thailand st case outside China https t co aCRPcTVwPx https t co b IBcgFW Update on me not catching the flu from my brother he text me from the room he s been quarantined in He needed foo https t co NSk Tlw o We got a new baby today She ll move into the big cage with natsu in maybe a week after shes quarantined but shes https t co tP PHOwgT Bourbon street bout to be quarantined Chinese woman with mysterious virus quarantined in Thailand https t co WszPiDwgfV A Chinese woman has been quarantined in Thailand with a mystery strain of coronavirus just days ahead of the Lunar https t co SmJO Fs K I had team mates international consultants quarantined in homestay on their retur https t co QYP gAktuw I don t know but they should be quarantined so as to not infect the rest of us Women that do this to anything other than a dick are gross specimens who need to be quarantined https t co xnRsS NXH A woman has been quarantined in Thailand First instance of de infection going international Thai Authorities ar https t co MALTvlJw You know you ve struck a nerve when replies start getting quarantined You need to be quarantined im RAINBOW evit has to keep me quarantined Chinese woman with mystery virus quarantined in Thailand https t co cgZpsvPnDP Thailand confirms first case of mystery virus from Wuhan Chinese woman quarantined https t co N StoxC s https t co C vmsc lR Chinese woman quarantined in Thailand is diagnosed with the same mystery virus that has killed one person in C https t co vrVScOl Jm Man charged after north east motorists crash into boulders and rubble shed from lorry https t co zjJWb IMi https t co U d MLjJmP Men are afraid They ve been told their life has to be lived a certain way and when it all crashes down he s left with r OTD in Thierry Sabine founder of the Paris Dakar Rally dies on a helicopter crash while taking part in the organi We ve all had that sinking feeling when we open a kitchen cupboard only to have everything come crashing down Follow these We ve all had that sinking feeling when we open a kitchen cupboard only to have everything come crashing down Fo https t co bZhE DCUJi American Media said that Iran had bulldozed the crash site of the shoot down What Iran did was relocate the wreckage It '